// Generated by the OpenNext build; keep its request context and streaming handler.
// @ts-ignore .open-next is generated at build time.
import handler from "../.open-next/worker.js";
import { recordCourseRequestPath } from "./course-request-path";
import { protectPersonalizedResponse } from "./cache-policy";
export { AppState } from "./app-state";
// @ts-ignore .open-next is generated at build time.
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "../.open-next/worker.js";

export default {
  async fetch(request: Request, env: unknown, ctx: ExecutionContext) {
    recordCourseRequestPath(ctx, request.url);
    return protectPersonalizedResponse(request, await handler.fetch(request, env, ctx));
  },
};
